### ISSUE TITLE
Failure/Error: ActiveRecord::Migration.maintain_test_schema!

### ISSUE THREAD

**Issue by Donnadieu** [learn-co-curriculum/rails-sidekiq-lab#9]
Steps to recreate:

1. Clone the repo

2. Run `bundle install`

3. Run `rake db:migrate`

We get the following error: 

```
An error occurred while loading ./spec/controllers/songs_controller_spec.rb.
Failure/Error: ActiveRecord::Migration.maintain_test_schema!

NoMethodError:
  undefined method `raise_in_transactional_callbacks=' for ActiveRecord::Base:Class
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-5.2.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-5.2.3/lib/active_record/railtie.rb:124:in `block (3 levels) in <class:Railti
e>'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-5.2.3/lib/active_record/railtie.rb:123:in `each'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-5.2.3/lib/active_record/railtie.rb:123:in `block (2 levels) in <class:Railti
e>'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'

# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-5.2.3/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-5.2.3/lib/active_record/base.rb:27:in `<top (required)>'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
# /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:598:in `maintain_test_schema!'
# ./spec/rails_helper.rb:31:in `<top (required)>'
# ./spec/controllers/songs_controller_spec.rb:1:in `require'
# ./spec/controllers/songs_controller_spec.rb:1:in `<top (required)>'


Finished in 0.03183 seconds (files took 4.34 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Solution; In `config/application.rb` line 33 comment out 
`config.active_record.raise_in_transactional_callbacks = true`

**Comment by maxwellbenton** [comment]
Hi @Donnadieu,

Thank you for opening this issue and bring this to our attention. We've identified that this lesson did not properly update for online students during a recent Ruby/Rails upgrade to our lessons. This lesson should no longer produce this error (repo was bumped to Rails 5, which rewrote `application.rb`).

Thank you for providing this feedback!
